package fr.herllox.hguide.Commands;

import org.bukkit.command.*;
import org.bukkit.entity.*;
import org.bukkit.*;
import java.util.*;
import org.bukkit.inventory.*;
import org.bukkit.inventory.meta.*;

public class GuideMenu implements CommandExecutor
{
    public boolean onCommand(final CommandSender sender, final Command cmd, final String msg, final String[] args) {
        final Player p = (Player)sender;
        final Inventory inv = Bukkit.createInventory((InventoryHolder)null, 45, "§b§lGuide§e§lMenu");
        final ItemStack i1 = new ItemStack(Material.GRASS_BLOCK);
        final ItemMeta i1x = i1.getItemMeta();
        i1x.setDisplayName("§aCr\u00e9er son Ile");
        i1x.setLore((List)Arrays.asList("", "§7Clique sur moi pour", "§7avoir des infos."));
        i1.setItemMeta(i1x);
        inv.setItem(11, i1);
        final ItemStack i2 = new ItemStack(Material.OAK_SIGN);
        final ItemMeta i2x = i2.getItemMeta();
        i2x.setDisplayName("§eIs Warp");
        i2x.setLore((List)Arrays.asList("", "§7Clique sur moi pour", "§7avoir des infos."));
        i2.setItemMeta(i2x);
        inv.setItem(12, i2);
        final ItemStack i3 = new ItemStack(Material.ENCHANTING_TABLE);
        final ItemMeta i3x = i3.getItemMeta();
        i3x.setDisplayName("§5Table d'Enchantement");
        i3x.setLore((List)Arrays.asList("", "§7Clique sur moi pour", "§7avoir des infos."));
        i3.setItemMeta(i3x);
        inv.setItem(13, i3);
        final ItemStack i4 = new ItemStack(Material.PLAYER_HEAD);
        final ItemMeta i4x = i4.getItemMeta();
        i4x.setDisplayName("§3Jouer \u00e0 plusieurs");
        i4x.setLore((List)Arrays.asList("", "§7Clique sur moi pour", "§7avoir des infos."));
        i4.setItemMeta(i4x);
        inv.setItem(14, i4);
        final ItemStack i5 = new ItemStack(Material.COBBLESTONE);
        final ItemMeta i5x = i5.getItemMeta();
        i5x.setDisplayName("§8Faire une usine \u00e0 cobble");
        i5x.setLore((List)Arrays.asList("", "§7Clique sur moi pour", "§7avoir des infos."));
        i5.setItemMeta(i5x);
        inv.setItem(15, i5);
        final ItemStack i6 = new ItemStack(Material.GOLD_INGOT);
        final ItemMeta i6x = i6.getItemMeta();
        i6x.setDisplayName("§6Shop");
        i6x.setLore((List)Arrays.asList("", "§7Clique sur moi pour", "§7avoir des infos."));
        i6.setItemMeta(i6x);
        inv.setItem(20, i6);
        final ItemStack i7 = new ItemStack(Material.ZOMBIE_HEAD);
        final ItemMeta i7x = i7.getItemMeta();
        i7x.setDisplayName("§9Ferme \u00e0 mobs");
        i7x.setLore((List)Arrays.asList("", "§7Clique sur moi pour", "§7avoir des infos."));
        i7.setItemMeta(i7x);
        inv.setItem(21, i7);
        final ItemStack i8 = new ItemStack(Material.FARMLAND);
        final ItemMeta i8x = i8.getItemMeta();
        i8x.setDisplayName("§bUsines automatiques");
        i8x.setLore((List)Arrays.asList("", "§7Clique sur moi pour", "§7avoir des infos."));
        i8.setItemMeta(i8x);
        inv.setItem(22, i8);
        final ItemStack i9 = new ItemStack(Material.ROSE_BUSH);
        final ItemMeta i9x = i9.getItemMeta();
        i9x.setDisplayName("§dFaire de la d\u00e9coration");
        i9x.setLore((List)Arrays.asList("", "§7Clique sur moi pour", "§7avoir des infos."));
        i9.setItemMeta(i9x);
        inv.setItem(23, i9);
        final ItemStack i10 = new ItemStack(Material.RED_STAINED_GLASS);
        final ItemMeta i10x = i10.getItemMeta();
        i10x.setDisplayName("§cChallenges");
        i10x.setLore((List)Arrays.asList("", "§7Clique sur moi pour", "§7avoir des infos."));
        i10.setItemMeta(i10x);
        inv.setItem(24, i10);
        final ItemStack i11 = new ItemStack(Material.EMERALD);
        final ItemMeta i11x = i11.getItemMeta();
        i11x.setDisplayName("§2Votes");
        i11x.setLore((List)Arrays.asList("", "§7Clique sur moi pour", "§7avoir des infos."));
        i11.setItemMeta(i11x);
        inv.setItem(29, i11);
        final ItemStack i12 = new ItemStack(Material.CHEST_MINECART);
        final ItemMeta i12x = i12.getItemMeta();
        i12x.setDisplayName("§aKits");
        i12x.setLore((List)Arrays.asList("", "§7Clique sur moi pour", "§7avoir des infos."));
        i12.setItemMeta(i12x);
        inv.setItem(30, i12);
        final ItemStack i13 = new ItemStack(Material.FEATHER);
        final ItemMeta i13x = i13.getItemMeta();
        i13x.setDisplayName("§7Fly");
        i13x.setLore((List)Arrays.asList("", "§7Clique sur moi pour", "§7avoir des infos."));
        i13.setItemMeta(i13x);
        inv.setItem(31, i13);
        final ItemStack i14 = new ItemStack(Material.EXPERIENCE_BOTTLE);
        final ItemMeta i14x = i14.getItemMeta();
        i14x.setDisplayName("§5Warps");
        i14x.setLore((List)Arrays.asList("", "§7Clique sur moi pour", "§7avoir des infos."));
        i14.setItemMeta(i14x);
        inv.setItem(32, i14);
        final ItemStack i15 = new ItemStack(Material.ENDER_EYE);
        final ItemMeta i15x = i15.getItemMeta();
        i15x.setDisplayName("§bMonde");
        i15x.setLore((List)Arrays.asList("", "§7Clique sur moi pour", "§7avoir des infos."));
        i15.setItemMeta(i15x);
        inv.setItem(33, i15);
        final ItemStack i16 = new ItemStack(Material.CHEST);
        final ItemMeta i16x = i15.getItemMeta();
        i16x.setDisplayName("§aEchange entre Joueurs");
        i16x.setLore((List)Arrays.asList("", "§7Clique sur moi pour", "§7avoir des infos."));
        i16.setItemMeta(i16x);
        inv.setItem(40, i16);
        p.openInventory(inv);
        return false;
    }
}
